FROM ubuntu

RUN apt-get update
RUN apt-get install -y python3
RUN apt-get install -y python3-pip
RUN pip3 install flask
RUN apt-get install -y git
RUN git clone https://github.com/mmumshad/simple-webapp-flask.git && cp simple-webapp-flask/app.py /opt/app.py
ENTRYPOINT  FLASK_APP=/opt/app.py flask run --host=0.0.0.0
